# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.11-slim

WORKDIR /app

# Copy project files including README for packaging
COPY pyproject.toml README.md ./
COPY src/ src/

# Install build dependencies (Hatchling) and application
RUN pip install --no-cache-dir .

# Default command to run the MCP server
ENTRYPOINT ["alibabacloud-dms-mcp-server"]
